version: "3.8"

services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/registration
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypass
      - ALLOWED_ORIGINS=http://51.250.42.156:3000
      #- ALLOWED_ORIGINS=http://localhost:3000
      # - JWT_SECRET=InnoSyncProd2025SecretKey987654321ForDeploymentUseOnlyChangeInProduction

  frontend:
    build:
      context: ./frontend/innosync
      args:
        NEXT_PUBLIC_API_URL: http://51.250.42.156:8080
        #NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://51.250.42.156:8080
      #- NEXT_PUBLIC_API_URL=http://localhost:8080
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: registration
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "registration"]
      interval: 5s
      retries: 5
